container:
  image: golang:latest

lint_task:
  check_script: gofmt -d ./*.go
  
docker_builder:
  depends_on:
    - lint
  build_script
    docker_build_script: docker build --tag imdhruva/splunk:latest . \
                        && docker run --rm -d imdhruva/splunk -p 8089:8089 -t test \
                        && docker inspect $(docker container ls -aq)
    test_script: go test

